#Advent of Code 2023
#Day 4: Scratchcards
#part 2: But make it insane
#v1.0  12-04-2023

import re

with open('Day4in.txt') as f:
    read_data = f.readlines()
f.close()

sumtot=0
cardcnt= {}   #copies OF this card
cardcpy = {}   #copies GENERATED by this card
for i in range(0,len(read_data)):
    matches =0
    cardID, winners, scratch =re.split(': |\| ',read_data[i].strip())
    cardID = cardID.replace("Card ","")
    cardID = cardID.replace(" ","")
    cardcnt.update({cardID:1})   #include original of card
    cardcpy.update({cardID:[]})   
    winners =re.split(' |  ', winners)  #convert to list
    scratch = re.split(' |  ', scratch)  #convert to list

#determine value of each card     
    for n in scratch:
         if n in winners and n != "":
             matches =matches+1
             #print("winner :", n, "match= ",matches, "new copy of card",  str(int(cardID)+matches))
             cardcpy[cardID].append(int(cardID)+matches)

for c in cardcpy.keys():
    exist = cardcnt[c]        #curr num of this card
    for x in cardcpy[c]:    # go through list this card creates
            count = cardcnt[str(x)]
            newcnt = exist + count 
            cardcnt.update({str(x):newcnt})            
    
#print("Copies made ", cardcpy)
#print("Tot copies", cardcnt)

for y in cardcnt.values():
    sumtot =sumtot+y
    
print("sumtot: ",sumtot)
